---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u1366952/public_html/FaizMarchendise/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
